### ISSUE TITLE
Different versions 

### ISSUE THREAD

**Issue by a55uka** [andrewnijmeh/food-memory-hack#1]
I know this is kind of a dumb question considering that there are probably protections in newer versions of minecraft but can this support other versions of minecraft, and if there is a protection how do you bypass it or use another method on it

**Comment by andrewn6** [comment]
First off, I'm not sure what you mean by "bypass" If you are talking about servers, you'll probably get banned instantly on any big servers like hypixel, MMC lunar etc. Anyways, Im not sure if I can even find the offsets for the different versions to do it. I only know the offset to it via a friend, But Idk about other ones for 1.8.9, etc. And really this program was used for fun and to mess around.
